name: 'Python Action'
inputs:
  target:
    description: 'Target'
    required: false

runs:
  using: composite
  steps:
    - name: 'Set variables'
      id: set-variables
      run: |
        [ -n "${{ inputs.target }}" ] && TARGET="${{ inputs.target }}" || TARGET="${{ github.repository_owner }}"
        echo "target=$TARGET" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: 'Run python scripts'
      working-directory: ${{ github.action_path }}/scripts
      run: |
        [ -f requirements.txt ] && pip install -r requirements.txt
        python main.py ${{ steps.set-variables.outputs.target }}
      shell: bash
