name: 'Python Action'
inputs:
  target:
    description: 'Target'
    required: false
runs:
  using: composite
  steps:
    - name: 'Set variables'
      id: set-variables
      run: |
        [ -n "${{ inputs.target }}" ] && TARGET="${{ inputs.target }}" || TARGET="${{ github.repository_owner }}"
        echo "TARGET=$TARGET" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: 'Run python scripts'
      run: python ./scripts/main.py ${{ steps.set-variables.outputs.TARGET }}
      shell: bash
