name: 'Test Local Action'

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target'
        type: string
        required: false

jobs:
  test-local-action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Set up python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        working-directory: './scripts'
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt
      - name: 'Test local action'
        uses: ./
        with:
          target: ${{ inputs.target }}
